# Generated by Django 3.0.1 on 2019-12-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadanganNomor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='None', max_length=25, verbose_name='Nama Pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=25, verbose_name='Nama')),
                ('paket', models.CharField(max_length=15)),
                ('ip_gpon', models.CharField(max_length=15, verbose_name='IP GPON')),
                ('slot_port', models.CharField(max_length=5, verbose_name='SLOT/PORT')),
                ('onu_id', models.CharField(max_length=2, verbose_name='ONU ID')),
                ('sn_ont', models.CharField(max_length=16, verbose_name='Serial Number ONT')),
                ('vendor', models.CharField(choices=[('ZTE', 'ZTE'), ('FH', 'FH'), ('HW', 'HW')], max_length=15, verbose_name='Vendor')),
                ('harga', models.FloatField(blank=True, verbose_name='Harga')),
                ('status', models.CharField(choices=[('Block', 'Block'), ('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'ordering': ['nama', 'pic__nama'],
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tg_fk', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_chat_user', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'User Telegram',
                'verbose_name_plural': 'User Telegram',
                'ordering': ['auth_user__first_name', 'auth_user__last_name', 'auth_user__username', 'auth_user__is_active'],
            },
        ),
        migrations.CreateModel(
            name='CadanganInet',
            fields=[
                ('cadangan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ca_inet_fk', serialize=False, to='indihome_app.CadanganNomor')),
                ('nomor', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
                ('paket', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('SAFETY', 'SAFETY'), ('DANGER', 'DANGER')], max_length=15, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('pelanggan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inet_fk', serialize=False, to='indihome_app.Pelanggan')),
                ('nomor', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_fk', to='indihome_app.Pic'),
        ),
        migrations.CreateModel(
            name='Iptv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=7)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptv_fk', to='indihome_app.Pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='CadanganIptv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('SAFETY', 'SAFETY'), ('DANGER', 'DANGER')], max_length=15, verbose_name='Status')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_iptv_fk', to='indihome_app.CadanganNomor')),
            ],
        ),
    ]
