# Generated by Django 3.0.1 on 2019-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indihome_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='vlan',
            field=models.IntegerField(default=1, verbose_name='VLAN'),
        ),
    ]
