# Generated by Django 3.0.1 on 2019-12-31 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indihome_app', '0002_pelanggan_vlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('ip', models.CharField(max_length=15, verbose_name='IP GPON')),
                ('vlan', models.IntegerField(default=1, verbose_name='VLAN')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='vlan',
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ip_gpon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpon_fk', to='indihome_app.Gpon'),
        ),
    ]
